import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Container } from "react-bootstrap";
import { StyledRoot } from "./@theme/styledRoot";
import "./globals.css";
import StyledComponentsRegistry from "./@core/lib/registry";
import GlobalStyles from "./@theme/GlobalStyles";

export const metadata: Metadata = {
  title: "Exemplo: ROUTE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`antialiased`}>
        <Container fluid>
          <AppRouterCacheProvider>
            <StyledComponentsRegistry>
              <GlobalStyles />
              <StyledRoot>{children}</StyledRoot>
            </StyledComponentsRegistry>
          </AppRouterCacheProvider>
        </Container>
      </body>
    </html>
  );
}
